package dev.shebang.devboard.view

import android.graphics.Matrix
import android.graphics.Path
import android.graphics.RectF
import androidx.core.graphics.PathParser

/**
 * Key glyphs as paths in a 24x24 box, all original to this project, in a terminal idiom: backspace is a
 * chevron erasing back toward a bar cursor, return a bent arrow with an open chevron head, shift a caret
 * that gains an underline while shift is on and doubles for caps lock. Scaled copies are built once per geometry.
 */
object KeyIcons {
    /** The shift caret turned to point left, and a bar cursor after it. */
    private const val BACKSPACE = "M5 12 L13.1 3.9 L14.5 5.3 L7.8 12 L14.5 18.7 L13.1 20.1 Z M17 6 H19 V18 H17 Z"
    /** Down from the top right, then left, ending in an open chevron. */
    private const val RETURN = "M19 4.5 H21 V15 H8.8 L11.9 18.1 L10.5 19.5 L5 14 L10.5 8.5 L11.9 9.9 L8.8 13 H19 Z"
    /** A caret pointing up. */
    private const val SHIFT = "M12 4.6 L20.1 12.7 L18.7 14.1 L12 7.4 L5.3 14.1 L3.9 12.7 Z"
    /** The caret with a bar under it: shift is on. */
    private const val SHIFT_ON = "$SHIFT M6.5 17.5 H17.5 V19.5 H6.5 Z"
    /** Two carets stacked over the bar: caps lock. */
    private const val SHIFT_LOCKED = "M12 3 L18.4 9.4 L17 10.8 L12 5.8 L7 10.8 L5.6 9.4 Z M12 8 L18.4 14.4 L17 15.8 L12 10.8 L7 15.8 L5.6 14.4 Z M6.5 17.5 H17.5 V19.5 H6.5 Z"

    /** A microphone: a capsule on a cradle and stand, with a block cursor as its foot. */
    private const val MIC = "M12 3 A3 3 0 0 1 15 6 V11 A3 3 0 0 1 9 11 V6 A3 3 0 0 1 12 3 Z " +
        "M5.5 11 H7.5 A4.5 4.5 0 0 0 16.5 11 H18.5 A6.5 6.5 0 0 1 13 17.4 V19 H11 V17.4 A6.5 6.5 0 0 1 5.5 11 Z " +
        "M9 19.5 H15 V21.5 H9 Z"

    /**
     * The Shebang mark, # and ! interlocked (the app icon's, in one colour), for the #! key. Generated by
     * tools/shebang_mark.py key from the same geometry as res/drawable/ic_launcher_foreground.xml.
     */
    private const val SHEBANG = "M11.79 4.40 L9.39 21.20 A1.4 1.4 0 0 1 6.61 20.80 L9.01 4.00 A1.4 1.4 0 0 1 11.79 4.40 Z M3.20 8.40 L14.75 8.40 L14.42 11.20 L3.20 11.20 A1.4 1.4 0 0 1 3.20 8.40 Z M19.96 8.40 L20.80 8.40 A1.4 1.4 0 0 1 20.80 11.20 L19.56 11.20 Z M2.40 14.00 L14.10 14.00 L13.78 16.80 L2.40 16.80 A1.4 1.4 0 0 1 2.40 14.00 Z M19.17 14.00 L20.00 14.00 A1.4 1.4 0 0 1 20.00 16.80 L18.77 16.80 Z M16.60 1.00 L20.00 1.00 L17.80 16.60 L14.80 16.60 Z M13.60 21.00 A2 2 0 1 1 17.60 21.00 A2 2 0 1 1 13.60 21.00 Z"

    /** A face: a ring, two block cursors for eyes, and a smile (the ring is cut out: even-odd). */
    private const val EMOJI = "M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z M5 12 A7 7 0 1 0 19 12 A7 7 0 1 0 5 12 Z " +
        "M8.5 8.5 H10.5 V11 H8.5 Z M13.5 8.5 H15.5 V11 H13.5 Z " +
        "M7.5 13 H9.5 A2.5 2.5 0 0 0 14.5 13 H16.5 A4.5 4.5 0 0 1 7.5 13 Z"

    /** A clipboard: a board with a solid clip on top and two lines of text. */
    private const val CLIPBOARD = "M5 5 H7 V21.5 H5 Z M17 5 H19 V21.5 H17 Z M7 19.5 H17 V21.5 H7 Z " +
        "M7 5 H9 V7 H7 Z M15 5 H17 V7 H15 Z M9 3 H15 V8 H9 Z M9 11 H15 V12.6 H9 Z M9 14.6 H13 V16.2 H9 Z"

    /** A gear with eight teeth and a round hole (even-odd): settings. */
    private const val GEAR = "M12.90 5.16 L14.25 2.98 L16.79 4.03 L16.20 6.53 L17.47 7.80 L19.97 7.21 L21.02 9.75 L18.84 11.10 L18.84 12.90 L21.02 14.25 L19.97 16.79 L17.47 16.20 L16.20 17.47 L16.79 19.97 L14.25 21.02 L12.90 18.84 L11.10 18.84 L9.75 21.02 L7.21 19.97 L7.80 17.47 L6.53 16.20 L4.03 16.79 L2.98 14.25 L5.16 12.90 L5.16 11.10 L2.98 9.75 L4.03 7.21 L6.53 7.80 L7.80 6.53 L7.21 4.03 L9.75 2.98 L11.10 5.16 Z M12 9 A3 3 0 1 0 12 15 A3 3 0 1 0 12 9 Z"

    /** A phone's outline with a small block of keys inside, low and to one side: one-handed mode. */
    private const val ONE_HANDED = "M5 2 H19 V22 H5 Z M7 4 V20 H17 V4 Z M8.5 12.5 H14 V18.5 H8.5 Z"

    /** One-handed mode's side panel: a chevron toward the side the keys move to, and a two-headed arrow for full width. */
    private const val DOCK_LEFT = "M14.6 4.5 L16 5.9 L9.9 12 L16 18.1 L14.6 19.5 L7.1 12 Z"
    private const val DOCK_RIGHT = "M9.4 4.5 L16.9 12 L9.4 19.5 L8 18.1 L14.1 12 L8 5.9 Z"
    private const val FULL_WIDTH = "M2.5 12 L7.5 7 L8.9 8.4 L6.3 11 H17.7 L15.1 8.4 L16.5 7 L21.5 12 L16.5 17 L15.1 15.6 L17.7 13 H6.3 L8.9 15.6 L7.5 17 Z"

    val backspace: Path = PathParser.createPathFromPathData(BACKSPACE)
    val shebang: Path = PathParser.createPathFromPathData(SHEBANG)
    val emoji: Path = PathParser.createPathFromPathData(EMOJI).apply { fillType = Path.FillType.EVEN_ODD }
    val clipboard: Path = PathParser.createPathFromPathData(CLIPBOARD)
    val mic: Path = PathParser.createPathFromPathData(MIC)
    val gear: Path = PathParser.createPathFromPathData(GEAR).apply { fillType = Path.FillType.EVEN_ODD }
    val oneHanded: Path = PathParser.createPathFromPathData(ONE_HANDED).apply { fillType = Path.FillType.EVEN_ODD }
    val dockLeft: Path = PathParser.createPathFromPathData(DOCK_LEFT)
    val dockRight: Path = PathParser.createPathFromPathData(DOCK_RIGHT)
    val fullWidth: Path = PathParser.createPathFromPathData(FULL_WIDTH)
    val enter: Path = PathParser.createPathFromPathData(RETURN)
    val shift: Path = PathParser.createPathFromPathData(SHIFT)
    val shiftOn: Path = PathParser.createPathFromPathData(SHIFT_ON)
    val shiftLocked: Path = PathParser.createPathFromPathData(SHIFT_LOCKED)

    private val matrix = Matrix()

    /** Copies [src] scaled and centred inside [bounds] at [size] pixels. Main thread only; allocates nothing. */
    fun fit(src: Path, size: Float, bounds: RectF, out: Path) {
        val m = matrix
        val s = size / 24f
        m.setScale(s, s)
        m.postTranslate(bounds.centerX() - size / 2f, bounds.centerY() - size / 2f)
        out.reset()
        src.transform(m, out)
        out.fillType = src.fillType
    }
}
